repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
      - id: end-of-file-fixer
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
      - id: check-builtin-literals
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
      - id: debug-statements
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
      - id: check-yaml
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
      - id: check-added-large-files
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ['--profile', 'black']
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --config-file=mypy.ini]
        files: models/notebooks/efc/results/.*\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.3.12
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
  - repo: local
    hooks:
      - id: pyclean
        name: pyclean
        entry: pyclean -v .
        language: python
        files: models/notebooks/efc/results/.*\.py$
        exclude: |
          (?x)^(
            models/notebooks/efc/efc_python/.*\.py$
          )
