name: Build LaTeX document and deploy
on:
  push:
  pull_request:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: dissertation_main.tex
          working_directory: .
          continue_on_error: true
          latexmk_shell_escape: true
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Exploring Machine Learning Techniques to Identify Fraudulent Crypto-currency Transactions: A Case Study at Mercado Bitcoin
          path: dissertation_main.pdf
